# Generated by Django 5.2 on 2025-05-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FlightTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight_number", models.CharField(max_length=100)),
                ("flight_status", models.CharField(max_length=100)),
                ("departure_time", models.CharField(max_length=100)),
                ("arrival_time", models.CharField(max_length=100)),
                ("departure_location", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["departure_time"],
            },
        ),
    ]
