# Generated by Django 5.2 on 2025-05-14 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_tracker", "0003_delete_booking"),
    ]

    operations = [
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row", models.IntegerField()),
                ("letter", models.CharField(max_length=1)),
                (
                    "seat_class",
                    models.CharField(
                        choices=[
                            ("FIRST", "First Class"),
                            ("BUSINESS", "Business Class"),
                            ("ECONOMY_PLUS", "Economy Plus"),
                            ("ECONOMY", "Economy"),
                        ],
                        max_length=20,
                    ),
                ),
                ("available", models.BooleanField(default=True)),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="flight_tracker.flighttracker",
                    ),
                ),
            ],
            options={
                "unique_together": {("flight", "row", "letter")},
            },
        ),
    ]
