# Generated by Django 5.2 on 2025-05-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_reference", models.CharField(max_length=100)),
                ("passenger_name", models.CharField(max_length=100)),
                ("seat", models.CharField(max_length=100)),
                ("extras", models.CharField(max_length=100)),
            ],
        ),
    ]
