# Generated by Django 5.2 on 2025-05-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticketing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight_number", models.CharField(max_length=100)),
                ("price", models.CharField(max_length=100)),
                ("class_type", models.CharField(max_length=100)),
                ("discount_code", models.CharField(max_length=100)),
                ("is_available", models.CharField(max_length=100)),
            ],
        ),
    ]
