# Generated by Django 5.2 on 2025-05-13 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_tracker", "0003_delete_booking"),
        ("ticketing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passenger", models.CharField(max_length=100)),
                (
                    "seat",
                    models.CharField(
                        choices=[
                            ("FIRST", "First Class"),
                            ("BUSINESS", "Business Class"),
                            ("ECONOMY_PLUS", "Economy Plus"),
                            ("ECONOMY", "Economy"),
                        ],
                        max_length=100,
                    ),
                ),
                ("check_in", models.BooleanField(default=False)),
                ("booking_time", models.DateTimeField(auto_now_add=True)),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking",
                        to="flight_tracker.flighttracker",
                    ),
                ),
            ],
        ),
    ]
