# Generated by Django 5.2 on 2025-05-14 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_tracker", "0004_seat"),
        ("ticketing", "0002_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="ticketing.ticketing",
            ),
        ),
        # migrations.AlterField(
        #     model_name="booking",
        #     name="seat",
        #     field=models.CharField(max_length=4),
        # ),
        # migrations.AlterField(
        #     model_name="ticketing",
        #     name="class_type",
        #     field=models.CharField(
        #         choices=[
        #             ("FIRST", "First Class"),
        #             ("BUSINESS", "Business Class"),
        #             ("ECONOMY_PLUS", "Economy Plus"),
        #             ("ECONOMY", "Economy"),
        #         ],
        #         max_length=20,
        #     ),
        # ),
        # migrations.AlterField(
        #     model_name="ticketing",
        #     name="discount_code",
        #     field=models.CharField(blank=True, max_length=100),
        # ),
        # migrations.AlterField(
        #     model_name="ticketing",
        #     name="is_available",
        #     field=models.BooleanField(default=True),
        # ),
        # migrations.AlterField(
        #     model_name="ticketing",
        #     name="price",
        #     field=models.DecimalField(decimal_places=2, max_digits=8),
        # ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Payment pending"),
                            ("PAID", "Payment successful"),
                            ("FAILED", "Payment Failed"),
                            ("REFUNDED", "Payment refunded"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="ticketing.booking",
                    ),
                ),
            ],
        ),
    ]
