# Generated by Django 5.2 on 2025-05-14 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_tracker", "0004_seat"),
        ("ticketing", "0003_booking_status_booking_ticket_alter_booking_seat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketing",
            name="flight",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="flight_tracker.flighttracker",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="flight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="flight_tracker.flighttracker",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="seat",
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name="ticketing",
            name="class_type",
            field=models.CharField(
                choices=[
                    ("FIRST", "First Class"),
                    ("BUSINESS", "Business Class"),
                    ("ECONOMY_PLUS", "Economy Plus"),
                    ("ECONOMY", "Economy"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ticketing",
            name="discount_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="ticketing",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="ticketing",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
